# esleasel by @joncoded (aka @jonchius)
# dictionary of strings 
# local.py 

l = {
  "en" : {
    "tagline" : "English language helper for all learners (a @joncoded project)",
    "ask_question" : "Ask a question", 
    "bullets" : "Bullet points",
    "discussion_history" : "Discussion history",
    "could_not_clear_namespace" : "Could not clear namespace", 
    "files_uploaded" : "File(s) uploaded",
    "idioms" : "Show and explain idioms", 
    "idioms_ex" : "like _break the ice_ or _hit the sack_", 
    "irregular_verbs" : "Show irregular verbs", 
    "irregular_verbs_ex" : "verbs like _teach (taught)_ and _go (went)_",    
    "learner_level" : "Your English level ([CEFR](https://gemini.google.com/app/07122657eb7689dc))",
    "level_a1" : "Beginner",
    "level_a2" : "Elementary",
    "level_b1" : "Intermediate",
    "level_b2" : "Upper-Intermediate",
    "level_c1" : "Advanced",
    "level_c2" : "Master",
    "loaded_chunks" : "Loaded chunks to database!",
    "loading_chunks" : "Loading chunks to database...",  
    "max_tokens" : "Maximum tokens for answer",
    "model_select" : "Select LLM (advanced)", 
    "new_vocab" : "Show new vocabulary",
    "new_vocab_ex" : "words that might be new to you", 
    "no_content_found" : "No content found",
    "no_content_to_summarize" : "No content to summarize", 
    "no_summary_could_be_made" : "No summary could be made",
    "pages_processed" : "Pages processed",
    "process_click_when_ready" : "click 'Process documents' when ready",
    "process_docs" : "Process documents",     
    "processing_docs" : "Processing documents...",
    "processed_file" : "Processed file", 
    "processing_file" : "Processing file...",
    "reset_everything" : "Reset everything",
    "reset_just_the_chat" : "Reset chat", 
    "sentences" : "How many sentences?",
    "settings" : "Settings", 
    "settings_about_you" : "About you",
    "settings_chat_answers" : "How would you like each chat message?",  
    "settings_docs_question" : "How long would you like each PDF summary?",    
    "splitted_documents" : "Documents splitted into chunks!",  
    "splitting_documents" : "Splitting document into chunks...",
    "start_over" : "Start over", 
    "submit_message" : "Submit", 
    "summary" : "Summary", 
    "summary_generating" : "Generating summary...",  
    "summary_of_documents" : "Summary of documents",    
    "temperature" : "Tone of answers",
    "temperature_formal" : "Formal",
    "temperature_casual" : "Casual",
    "temperature_crazy" : "Eccentric?",
    "thinking" : "Thinking...",  
    "files_and_settings" : "Change files and settings...", 
    "upload_documents" : "Upload an English PDF to understand it better!",
    "upload_instructions" : "You can upload one (or more) PDF file(s):",
    "yes": "Yes",
    "no": "No"
  },
  "fr": {      
    "tagline" : "assistant de langue anglaise pour tous les apprenants (par @joncoded)",
    "ask_question" : "Veuillez poser une question (en anglais seulement pour l'instant)", 
    "bullets" : "Puces en liste",
    "discussion_history" : "Historique de la discussion",
    "could_not_clear_namespace" : "Impossible de vider l'espace de noms", 
    "files_uploaded" : "Fichier(s) téléchargé(s)",
    "idioms" : "Afficher et expliquer les idiomes*",
    "idioms_ex" : "* - expressions comme _break the ice_ ou _hit the sack_",
    "irregular_verbs" : "Afficher les verbes irréguliers", 
    "irregular_verbs_ex" : "verbes comme _teach (taught)_ et _go (went)_",    
    "learner_level" : "Votre niveau d'anglais ([CEFR](https://gemini.google.com/app/07122657eb7689dc))",
    "level_a1" : "Débutant",
    "level_a2" : "Élémentaire",
    "level_b1" : "Intermédiaire",
    "level_b2" : "Indépendant",
    "level_c1" : "Autonome",
    "level_c2" : "Maîtrise",
    "loaded_chunks" : "Morceaux chargés dans la base de données !",
    "loading_chunks" : "Chargement des morceaux dans la base de données...",
    "max_tokens" : "Nombre maximum de tokens pour la réponse",
    "model_select" : "Sélectionnez LLM (avancé)",
    "new_vocab" : "Afficher le nouveau vocabulaire",
    "new_vocab_ex" : "mots qui pourraient être nouveaux pour vous",
    "no_content_found" : "Aucun contenu trouvé",
    "no_content_to_summarize" : "Aucun contenu à résumer", 
    "no_summary_could_be_made" : "Aucun sommaire n'a pu être fait",
    "pages_processed" : "Pages traitées",
    "process_click_when_ready" : "cliquez sur 'Traiter les documents' lorsque vous êtes prêt",
    "process_docs" : "Traiter les documents",     
    "processing_docs" : "Traitement des documents...",
    "processed_file" : "Fichier traité", 
    "processing_file" : "Traitement du fichier...",
    "reset_everything" : "Tout réinitialiser",
    "reset_just_the_chat" : "Réinitialiser le chat", 
    "sentences" : "Combien de phrases ?",
    "settings" : "Paramètres",
    "settings_about_you" : "À propos de vous",
    "settings_docs_question" : "Comment souhaitez-vous configurer chaque PDF ?",    
    "settings_chat_answers" : "Comment souhaitez-vous configurer chaque message du chat ?",  
    "splitted_documents" : "Documents divisés en morceaux",  
    "splitting_documents" : "Division des documents en morceaux...",
    "start_over" : "Recommencer", 
    "submit_message" : "Soumettre", 
    "summary" : "Résumé", 
    "summary_generating" : "Génération du résumé...",
    "summary_of_documents" : "Résumé des documents", 
    "temperature" : "Ton des réponses",
    "temperature_formal" : "Formel",
    "temperature_casual" : "Décontracté",
    "temperature_crazy" : "Excentrique?",
    "thinking" : "Réflexion...",
    "files_and_settings" : "Changer les fichiers et les paramètres...", 
    "upload_documents" : "Téléchargez un PDF en anglais pour le comprendre mieux !",
    "upload_instructions" : "Téléchargez un (ou plusieurs) fichier PDF à comprendre (limite : 5Mo chacun)",
    "yes": "Oui",
    "no": "Non"
  },
}